---
# the main.yml file will simply be used to include necessary other task files

- include_tasks: install.yml

- name: configure mounts if they are specified
  include_tasks: config.yml
  when: mounts is defined
